import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import "./globals.scss";

const bebas = Bebas_Neue({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//Title, Rated, Release date, Runtime, Genres, Short plot, Poster img, ratings
//file based router

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth no-scrollbar">
      <body className={bebas.className + " bg-mainBgGrey"}>{children}</body>
    </html>
  );
}
